project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - project-log.qmd
    - wikidata.qmd
    - ausstellung.qmd
    - wikidata-item.ipynb

title: "BIM Prototype 02"
metadata:
  author:
    - name: "Julia Schessler"
      orcid: "0009-0007-6477-3191"

website:
  title: "BIM Prototype 02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project-log.qmd
        text: Project Log
      - href: wikidata.qmd
        text: Wikidata
      - href: ausstellung.qmd
        text: Ausstellung
      - href: wikidata-item.ipynb
        text: Item Profile

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
